train:

# Evaluation only mode
eval_only: false  # Set to true to only run evaluation on test set
checkpoint: null  # Path to log folder containing config.yaml and best_model.pth (e.g., "log/FakeSV_0818-143022")

data:
  tokenizer_name: "OFA-Sys/chinese-clip-vit-large-patch14"
  include_piyao: true  # Whether to include '辟谣' (rumor debunking) labels, mapped to real (0)
  ablation_no_cot: false  # Ablation study: remove CoT text features, use only video features
  ablation_no_vision: false  # Ablation study: remove visual features, use only text features
para:
  hid_dim: 256
  dropout: 0.3
  text_encoder: "OFA-Sys/chinese-clip-vit-large-patch14"
  num_frozen_layers: 4
  # Cross-modal transformer parameters
  cross_modal: true  # Toggle transformer fusion (default: false for backward compatibility)
  cross_modal_layers: 4
  cross_modal_heads: 8
  cross_modal_dim_ff: 1024
  cross_modal_dropout: 0.1
opt:
  name: AdamW
  lr: 5e-5
  weight_decay: 5e-4
sche:
  name: DummyLR
num_epoch: 15
batch_size: 32
text_encoder: "OFA-Sys/chinese-clip-vit-large-patch14"
seed: 2024
model: ExMRD
dataset: FakeSV
type: temporal
patience: 5