train:

data:
  tokenizer_name: "OFA-Sys/chinese-clip-vit-large-patch14"
  include_piyao: false  # Whether to include '辟谣' (rumor debunking) labels, mapped to real (0)
  description: false      # If true, include description in text concatenation
  temp_evolution: false   # If true, include temporal_evolution in text concatenation
  # Modality control parameters
  use_text: true         # If true, use text features
  use_image: true        # If true, use visual/image features
  use_audio: true        # If true, use audio features
  
para:
  hid_dim: 256
  dropout: 0.3
  text_encoder: "OFA-Sys/chinese-clip-vit-large-patch14"
  num_frozen_layers: 4
  # Model architecture parameters
  use_evidential: false  # If false, use traditional concatenation + classifier
  # Traditional model specific parameters
  evidential_hidden: 256
  evidential_dropout: 0.1
  anneal_steps: 1000
  loss_weights:
    fused: 1.0
    text: 1
    audio: 0.5
    image: 0.5

opt:
  name: AdamW
  lr: 5e-5
  weight_decay: 5e-4
  
sche:
  name: DummyLR
  
num_epoch: 15
batch_size: 32
text_encoder: "OFA-Sys/chinese-clip-vit-large-patch14"
seed: 2024
model: ExMRD_Evidential
dataset: FakeSV
type: temporal
patience: 5

# Evaluation parameters
eval_only: false  # Set to true for evaluation only mode
checkpoint: null  # Path to checkpoint for evaluation only mode